const SET_USER = "SET_USER";
const STORE_USER = "STORE_USER";

const SET_IS_LOADING = "SET_IS_LOADING";
const SET_SOFTWARE_DETAIL = "SET_SOFTWARE_DETAIL";
const SET_IS_SHOW_PREDICTION = "SET_IS_SHOW_PREDICTION";
const SET_SEARCH_PREDICTION = "SET_SEARCH_PREDICTION";

const SET_SEARCH_PARAMS = "SET_SEARCH_PARAMS";

const SET_FILTER_LISTS = "SET_FILTER_LISTS";

const SET_SHOW_PROFILE_MODAL = "SET_SHOW_PROFILE_MODAL";
const SET_SHOW_CART_OVERLAY = "SET_SHOW_CART_OVERLAY";
const SET_LOCALE = "SET_LOCALE";
const SET_ISLOGPAGE = "SET_ISLOGPAGE";
const GO_TO_PAGE = "GO_TO_PAGE";
const INIT_GO_TO_PAGE = "INIT_GO_TO_PAGE";

const ADD_INTO_CART_LIST = "ADD_INTO_CART_LIST";
const REMOVE_FROM_CART_LIST = "REMOVE_FROM_CART_LIST";
const CLEAR_CART_LIST = "CLEAR_CART_LIST";
const UPDATE_CART_LIST = "UPDATE_CART_LIST";

const ADD_INTO_DETAILS = "ADD_INTO_DETAILS";
const EDIT_DETAILS = "EDIT_DETAILS";
const REMOVE_FROM_DETAILS = "REMOVE_FROM_DETAILS";
const REMOVE_FROM_DETAILS_BY_ID = "REMOVE_FROM_DETAILS_BY_ID";
const CLEAR_DETAILS = "CLEAR_DETAILS";

const SHOW_ALERT_MESSAGE = "SHOW_ALERT_MESSAGE";
const TOGGLE_ALERT = "TOGGLE_ALERT";
const TOGGLE_SNACKBAR = "TOGGLE_SNACKBAR";
const SHOW_SNACKBAR_MESSAGE = "SHOW_SNACKBAR_MESSAGE";

const SET_PERMISSIONS = "SET_PERMISSIONS";
const SET_DASHBOARD_DATA = "SET_DASHBOARD_DATA";
const SET_ADMIN_USERS = "SET_ADMIN_USERS";
const SET_ADMIN_USERS_LIST = "SET_ADMIN_USERS_LIST";
const SET_ROLE_LIST = "SET_ROLE_LIST";

const SET_VIP_LIST = "SET_VIP_LIST";
const SET_SITE_LIST = "SET_SITE_LIST";
const SET_SITE = "SET_SITE";
const SET_QUERY_FILTERS = "SET_QUERY_FILTERS";
const SET_EFORM_QUERY_RESULTS = "SET_EFORM_QUERY_RESULTS";
const SET_SOFTWARE_QUERY_RESULTS = "SET_SOFTWARE_QUERY_RESULTS";

const SET_DATA_AUTH_LIST = "SET_DATA_AUTH_LIST";

const SET_BGBU_LIST = "SET_BGBU_LIST";

const SET_SCCM_INFO_LIST = "SET_SCCM_INFO_LIST";
const SET_LICENSE_INFO_LIST = "SET_LICENSE_INFO_LIST";
const SET_STOCK_ID_LIST = "SET_STOCK_ID_LIST";
const SET_INSTALLATION_PATH_LIST = "SET_INSTALLATION_PATH_LIST";

const SET_SIDEBAR_LIST = "SET_SIDEBAR_LIST";

const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";

const SET_VERIFIED_COST_DEPT = "SET_VERIFIED_COST_DEPT";

const SET_SDP_MANUAL_INFO = "SET_SDP_MANUAL_INFO";
const SET_SDP_UNPROCESSED_INFO = "SET_SDP_UNPROCESSED_INFO";
const SET_SDP_PROCESSED_INFO = "SET_SDP_PROCESSED_INFO";

const SET_RATE_LIST = "SET_RATE_LIST";
const SET_VIEWRATE_LIST = "SET_VIEWRATE_LIST";
const SET_SW_AUTHORITY_MGT_LIST = "SET_SW_AUTHORITY_MGT_LIST";
const SET_EXPORT_SW_AUTHORITY_MGT_LIST = "SET_EXPORT_SW_AUTHORITY_MGT_LIST";
const SET_SW_PLAN_LIST = "SET_SW_PLAN_LIST";
const SET_PLAN_BEGIN_DATE = "SET_PLAN_BEGIN_DATE";
const SET_RATE_CODE = "SET_RATE_CODE";
const SET_SWIMPORT_MSG = "SET_SWIMPORT_MSG";

const SET_SAM_FUNCTION_LIST = "SET_SAM_FUNCTION_LIST";
const SET_TOGGLE_TOKEN_MODAL = "SET_TOGGLE_TOKEN_MODAL";
const SET_SWITCHED_USER_TOKEN = "SET_SWITCHED_USER_TOKEN";

const SET_E_FORM_LIST = "SET_E_FORM_LIST";
const SET_SDP_I18N_MESSAGE = "SET_SDP_I18N_MESSAGE";

const SET_CATEGORY_ID = "SET_CATEGORY_ID";

const GET_FREEWARE_REVIEW_LIST = "GET_FREEWARE_REVIEW_LIST";
const SET_FREEWARE_REVIEW_LIST = "SET_FREEWARE_REVIEW_LIST";
export default {
  SET_USER,
  STORE_USER,

  SET_IS_LOADING,
  SET_SOFTWARE_DETAIL,
  SET_IS_SHOW_PREDICTION,
  SET_SEARCH_PREDICTION,

  SET_SEARCH_PARAMS,
  SET_FILTER_LISTS,

  SET_SHOW_PROFILE_MODAL,
  SET_SHOW_CART_OVERLAY,
  SET_LOCALE,
  SET_ISLOGPAGE,

  GO_TO_PAGE,
  INIT_GO_TO_PAGE,

  ADD_INTO_DETAILS,
  EDIT_DETAILS,
  REMOVE_FROM_DETAILS,
  CLEAR_DETAILS,
  ADD_INTO_CART_LIST,
  REMOVE_FROM_CART_LIST,
  CLEAR_CART_LIST,
  UPDATE_CART_LIST,
  REMOVE_FROM_DETAILS_BY_ID,

  SHOW_ALERT_MESSAGE,
  TOGGLE_ALERT,
  TOGGLE_SNACKBAR,
  SHOW_SNACKBAR_MESSAGE,

  SET_PERMISSIONS,
  SET_DASHBOARD_DATA,
  SET_ADMIN_USERS,
  SET_ADMIN_USERS_LIST,
  SET_ROLE_LIST,

  SET_PERMISSIONS,
  SET_ADMIN_USERS,
  SET_ADMIN_USERS_LIST,
  SET_ROLE_LIST,

  SET_VIP_LIST,
  SET_SITE_LIST,
  SET_SITE,
  SET_E_FORM_LIST,

  SET_QUERY_FILTERS,
  SET_EFORM_QUERY_RESULTS,
  SET_SOFTWARE_QUERY_RESULTS,

  SET_DATA_AUTH_LIST,

  SET_BGBU_LIST,

  SET_SCCM_INFO_LIST,
  SET_LICENSE_INFO_LIST,
  SET_STOCK_ID_LIST,
  SET_CATEGORY_ID,
  SET_INSTALLATION_PATH_LIST,

  SET_SIDEBAR_LIST,

  SET_CATEGORY_LIST,

  SET_VERIFIED_COST_DEPT,

  SET_SDP_MANUAL_INFO,
  SET_SDP_UNPROCESSED_INFO,
  SET_SDP_PROCESSED_INFO,

  SET_RATE_LIST,
  SET_VIEWRATE_LIST,
  SET_RATE_CODE,

  SET_SW_AUTHORITY_MGT_LIST,
  SET_EXPORT_SW_AUTHORITY_MGT_LIST,
  SET_SWIMPORT_MSG,
  SET_SW_PLAN_LIST,
  SET_PLAN_BEGIN_DATE,
  SET_SAM_FUNCTION_LIST,
  SET_TOGGLE_TOKEN_MODAL,
  SET_SWITCHED_USER_TOKEN,
  SET_SDP_I18N_MESSAGE,
};
