const SET_USER = "SET_USER";
const STORE_USER = "STORE_USER";

const SET_IS_LOADING = "SET_IS_LOADING";

const SET_SHOW_PROFILE_MODAL = "SET_SHOW_PROFILE_MODAL";
const SET_SHOW_CART_OVERLAY = "SET_SHOW_CART_OVERLAY";
const SET_LOCALE = "SET_LOCALE";
const SET_ISLOGPAGE = "SET_ISLOGPAGE";
const GO_TO_PAGE = "GO_TO_PAGE";

const SHOW_ALERT_MESSAGE = "SHOW_ALERT_MESSAGE";
const TOGGLE_ALERT = "TOGGLE_ALERT";
const TOGGLE_SNACKBAR = "TOGGLE_SNACKBAR";
const SHOW_SNACKBAR_MESSAGE = "SHOW_SNACKBAR_MESSAGE";

const SET_PERMISSIONS = "SET_PERMISSIONS";
const SET_ADMIN_USERS = "SET_ADMIN_USERS";
const SET_ADMIN_USERS_LIST = "SET_ADMIN_USERS_LIST";
const SET_ROLE_LIST = "SET_ROLE_LIST";

const SET_SIDEBAR_LIST = "SET_SIDEBAR_LIST";

const SET_SAM_FUNCTION_LIST = "SET_SAM_FUNCTION_LIST";
const SET_TOGGLE_TOKEN_MODAL = "SET_TOGGLE_TOKEN_MODAL";
const SET_SWITCHED_USER_TOKEN = "SET_SWITCHED_USER_TOKEN";

//---------new 
const GET_USER = "GET_USER";
const GET_APP_LIST = "GET_APP_LIST";
const GET_REQUEST_LIST = "GET_REQUEST_LIST";
const SEND_UNINSTALL_APPLICATION = "SEND_UNINSTALL_APPLICATION";
const SET_REQUEST_LIST = "SET_REQUEST_LIST";
const SET_TASK_INFO_LIST = "SET_TASK_INFO_LIST"
const GET_TASK_INFO_LIST = "GET_TASK_INFO_LIST"
export default {
  SET_USER,
  STORE_USER,

  SET_IS_LOADING,

  SET_SHOW_PROFILE_MODAL,
  SET_SHOW_CART_OVERLAY,
  SET_LOCALE,
  SET_ISLOGPAGE,

  GO_TO_PAGE,

  SHOW_ALERT_MESSAGE,
  TOGGLE_ALERT,
  TOGGLE_SNACKBAR,
  SHOW_SNACKBAR_MESSAGE,

  SET_PERMISSIONS,
  SET_ADMIN_USERS,
  SET_ADMIN_USERS_LIST,
  SET_ROLE_LIST,

  SET_SIDEBAR_LIST,
  SET_SAM_FUNCTION_LIST,
  SET_TOGGLE_TOKEN_MODAL,
  SET_SWITCHED_USER_TOKEN,

  //-------------------new
  GET_USER,
  GET_APP_LIST,
  GET_REQUEST_LIST,
  SEND_UNINSTALL_APPLICATION,
  SET_REQUEST_LIST,

  //-------------------TASK_INFO
  SET_TASK_INFO_LIST,
  GET_TASK_INFO_LIST,
};
